[package]
name = "oneil"
description = "CLI tool for using the Oneil programming language"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
oneil_ast = { path = "../oneil_ast" }
oneil_model_loader = { path = "../oneil_model_loader" }
oneil_parser = { path = "../oneil_parser" }
oneil_unit_checker = { path = "../oneil_unit_checker" }
clap = { version = "4.5.1", features = ["derive"] }
