[package]
name = "oneil"
description = "CLI tool for using the Oneil programming language"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
oneil_ast = { path = "../oneil_ast" }
oneil_error = { path = "../oneil_error" }
oneil_ir = { path = "../oneil_ir" }
oneil_model_resolver = { path = "../oneil_model_resolver" }
oneil_parser = { path = "../oneil_parser" }
clap = { version = "4.5.1", features = ["derive"] }
colored = "3.0.0"

[lints]
workspace = true
